services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: nxus
      POSTGRES_PASSWORD: nox
      POSTGRES_DB: pomohubdb 
    volumes:
      - postgre-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgre-data:
